### ISSUE TITLE
NewTab Navigate

### ISSUE THREAD

**Issue by 5k3105** [wirepair/gcd#5] opened 2016-03-07 23:15 UTC
Calling this function, I get an 'about:blank' tab:

```go
func gotoSite() {

	target, _ := debugger.NewTab()
	target.Page.Enable()
	target.Page.Navigate("http://google.com")

}
```
What did I do wrong?
Thanks.

**Comment by wirepair** [comment] 2016-03-08 00:09
Hard to tell since you are ignoring errors (are you getting any?)
Does this snippit work?

```
package main

import (
	"github.com/wirepair/gcd"
	"log"
	"sync"
)

func main() {
	debugger := gcd.NewChromeDebugger()
	debugger.StartProcess("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "/tmp/", "9222")
	defer debugger.ExitProcess() // exit when done

	target, err := debugger.NewTab()
	if err != nil {
		log.Fatal("error: %s\n", err)
	}
	wg := &sync.WaitGroup{}
	wg.Add(1)
	target.Page.Enable()
	_, err = target.Page.Navigate("http://google.com")
	if err != nil {
		log.Fatal("error: %s\n", err)
	}
	wg.Wait()
}

**Comment by 5k3105** [comment] 2016-03-08 00:29
Hi,

I'm starting the debugger process in an application with a button. The debugger is global context. When button is clicked, tab opens but doesn't navigate to url.

Your code works. The code I used of yours is everything after the defer statement. Debugger is still running and global because the tab opens. I get no errors.

Running windows. Wishing the sync stuff would have changed something but it seems to have no effect.

Thanks

**Comment by wirepair** [comment] 2016-03-08 00:31
if you could send me your exact code, or a reduced working set of it, i can test it out on my windows box later.

**Comment by 5k3105** [comment] 2016-03-08 01:09
I'm using [https://github.com/therecipe/qt](url). It's a lot of setup for one example. Can't think of anything else to simulate this.

Not sure what else to think is wrong. With qt, I connect the gotoSite function to the TreeClicked event. In that code it just opens a tab, enables the page and navigates like the above code. Only the tab opens. The page doesn't navigate.

**Comment by wirepair** [comment] 2016-03-08 01:30
Just out of curiosity did you try my other library that was meant for automation (autogcd?) https://github.com/wirepair/autogcd. It still uses gcd under the hood but abstracts a lot of the stuff for automation purposes.

**Comment by 5k3105** [comment] 2016-03-08 02:00
Using autogcd example [https://github.com/wirepair/autogcd/blob/master/examples/googler/googler.go](url), I had to change line 47 to a hardcoded dir 'C:\\\temp".
It opens up the tab, goes to first link in jp, then stops after google search for gcd. 

```
C:/Go/bin/go.exe build -i [C:/Users/5k3105/goworksp/src/Local/crom/test_newautotab]
Success: process exited with code 0.
C:/Users/5k3105/goworksp/src/Local/crom/test_newautotab/test_newautotab.exe  [C:/Users/5k3105/goworksp/src/Local/crom/test_newautotab]
2016/03/07 18:51:04 navigation complete
2016/03/07 18:51:04 getting search element
2016/03/07 18:51:04 sending keys
2016/03/07 18:51:04 waiting for stability
2016/03/07 18:51:06 getting search elements
2016/03/07 18:51:06 found the best link there is
2016/03/07 18:51:06 clicking google link
2016/03/07 18:51:11 here we are, bask in its glory
2016/03/07 18:51:16 Done
panic: chrome was terminated: exit status 1


goroutine 5 [running]:
github.com/wirepair/autogcd.(*AutoGcd).defaultTerminationHandler(0xc0820528d0, 0xc08221d3c0, 0xd)
	C:/Users/5k3105/goworksp/src/github.com/wirepair/autogcd/autogcd.go:92 +0x156
github.com/wirepair/autogcd.(*AutoGcd).(github.com/wirepair/autogcd.defaultTerminationHandler)-fm(0xc08221d3c0, 0xd)
	C:/Users/5k3105/goworksp/src/github.com/wirepair/autogcd/autogcd.go:71 +0x3b
github.com/wirepair/gcd.(*Gcd).StartProcess.func1(0xc0820665a0)
	C:/Users/5k3105/goworksp/src/github.com/wirepair/gcd/gcd.go:141 +0x1cc
created by github.com/wirepair/gcd.(*Gcd).StartProcess
	C:/Users/5k3105/goworksp/src/github.com/wirepair/gcd/gcd.go:143 +0x93c

goroutine 1 [syscall, locked to thread]:
syscall.Syscall(0x76d61840, 0x2, 0x245560, 0xc08265d6dc, 0x0, 0x60, 0x7cf7a0, 0x0)
	c:/go/src/runtime/syscall_windows.go:128 +0x5c
syscall.GetConsoleMode(0x245560, 0xc08265d6dc, 0x0, 0x0)
	c:/go/src/syscall/zsyscall_windows.go:1238 +0x70
os.newFile(0x245560, 0xc0823c9a40, 0x19, 0x0)
	c:/go/src/os/file_windows.go:53 +0xd7
os.openDir(0xc0823c9a40, 0x19, 0x0, 0x0, 0x0)
	c:/go/src/os/file_windows.go:127 +0x404
os.OpenFile(0xc0823c9a40, 0x19, 0x0, 0x0, 0x2580050, 0x0, 0x0)
	c:/go/src/os/file_windows.go:145 +0x237
os.Open(0xc0823c9a40, 0x19, 0x2584610, 0x0, 0x0)
	c:/go/src/os/file.go:246 +0x4f
os.RemoveAll(0xc0823c9a40, 0x19, 0x0, 0x0)
	c:/go/src/os/path.go:87 +0x252
os.RemoveAll(0xc082140250, 0xf, 0x0, 0x0)
	c:/go/src/os/path.go:102 +0x413
os.RemoveAll(0x8073a8, 0x7, 0x0, 0x0)
	c:/go/src/os/path.go:102 +0x413
github.com/wirepair/autogcd.(*AutoGcd).Shutdown(0xc0820528d0, 0x0, 0x0)
	C:/Users/5k3105/goworksp/src/github.com/wirepair/autogcd/autogcd.go:134 +0x243
main.main()
	C:/Users/5k3105/goworksp/src/Local/crom/test_newautotab/autotab.go:106 +0x110d

goroutine 17 [select]:
net/http.(*persistConn).readLoop(0xc0820780b0)
	c:/go/src/net/http/transport.go:976 +0xace
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:685 +0xc7f

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc0820780b0)
	c:/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:686 +0xca4
Error: process exited with code 2.
```

**Comment by wirepair** [comment] 2016-03-08 02:06
that's weird because it clearly didn't fail, if it didn't find / click the links it would have thrown an error. Wonder if chrome isn't redrawing fast enough or something. What version of chrome are you using?

**Comment by 5k3105** [comment] 2016-03-08 02:07
Version 48.0.2564.116 m

**Comment by 5k3105** [comment] 2016-03-08 02:09
It stays on the google response to "github gcd" for a few seconds then crashes.

**Comment by wirepair** [comment] 2016-03-08 05:39
it's actually not crashing, it's panic'ing because the defaultTerminationHandler isn't set, See https://github.com/wirepair/autogcd/blob/master/autogcd_test.go#L129 for how to set a termination handler. 

Again it should have error'd out if any of those previous steps failed, note how it's successfully passing the error statements log.Fatal? https://github.com/wirepair/autogcd/blob/master/examples/googler/googler.go#L72

**Comment by wirepair** [comment] 2016-03-08 05:42
Anyways, i'll look at this tonight in windows, maybe i can reproduce your issue.

**Comment by wirepair** [comment] 2016-03-08 11:39
Just confirmed it worked on my windows machine, same output you had except i can see it actually get to the github page. Are you running in a VM or via RDP or something else that would cause it not to actually draw the page? Try setting the time.Sleep to a longer value and move the window around or something?

my output: 
C:\gohome\src\github.com\wirepair\autogcd\examples\googler>go run googler.go
2016/03/08 20:36:24 navigation complete
2016/03/08 20:36:24 getting search element
2016/03/08 20:36:24 sending keys
2016/03/08 20:36:24 waiting for stability
2016/03/08 20:36:25 getting search elements
2016/03/08 20:36:25 found the best link there is
2016/03/08 20:36:25 clicking google link
2016/03/08 20:36:26 here we are, bask in its glory
2016/03/08 20:36:31 Done
panic: chrome was terminated: exit status 1


goroutine 5 [running]:
github.com/wirepair/autogcd.(*AutoGcd).defaultTerminationHandler(0xc08204e9c0, 0xc0827ce190, 0xd)
        C:/gohome/src/github.com/wirepair/autogcd/autogcd.go:92 +0x156
github.com/wirepair/autogcd.(*AutoGcd).(github.com/wirepair/autogcd.defaultTerminationHandler)-fm(0xc0827ce190, 0xd)
        C:/gohome/src/github.com/wirepair/autogcd/autogcd.go:71 +0x3b
github.com/wirepair/gcd.(*Gcd).StartProcess.func1(0xc08206c500)
        C:/gohome/src/github.com/wirepair/gcd/gcd.go:141 +0x1cc
created by github.com/wirepair/gcd.(*Gcd).StartProcess
        C:/gohome/src/github.com/wirepair/gcd/gcd.go:143 +0x93c

goroutine 1 [runnable, locked to thread]:
syscall.Syscall(0x7ffe3929d8e0, 0x1, 0xc082086000, 0x0, 0x0, 0x57, 0x57, 0x0)
        c:/go/src/runtime/syscall_windows.go:128 +0x5c
syscall.DeleteFile(0xc082086000, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:447 +0x6f
os.Remove(0xc082742240, 0x56, 0x0, 0x0)
        c:/go/src/os/file_windows.go:441 +0x170
os.RemoveAll(0xc082742240, 0x56, 0x0, 0x0)
        c:/go/src/os/path.go:123 +0x4f2
os.RemoveAll(0xc0822a60a0, 0x4c, 0x0, 0x0)
        c:/go/src/os/path.go:102 +0x413
os.RemoveAll(0xc082555410, 0x2b, 0x0, 0x0)
        c:/go/src/os/path.go:102 +0x413
os.RemoveAll(0xc0820d5d20, 0x20, 0x0, 0x0)
        c:/go/src/os/path.go:102 +0x413
os.RemoveAll(0xc08200ad60, 0x18, 0x0, 0x0)
        c:/go/src/os/path.go:102 +0x413
github.com/wirepair/autogcd.(*AutoGcd).Shutdown(0xc08204e9c0, 0x0, 0x0)
        C:/gohome/src/github.com/wirepair/autogcd/autogcd.go:134 +0x243
main.main()
        C:/gohome/src/github.com/wirepair/autogcd/examples/googler/googler.go:105 +0x1110

goroutine 33 [select]:
net/http.(*persistConn).readLoop(0xc082098210)
        c:/go/src/net/http/transport.go:976 +0xace
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xc7f

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc082098210)
        c:/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xca4
exit status 2

**Comment by 5k3105** [comment] 2016-03-08 17:58
Moving the window worked. It seems like if the window is not full screen it doesn't show the last navigation. If it is full screen it shows everything. If I move the window around while it's trying to load pages it stops loading pages.

**Comment by wirepair** [comment] 2016-03-09 09:15
Bizarre, i've never seen that before. I wonder if calling autogcd.ActivateTab(tab) before navigating/after navigating would cause a redraw?. Anyways i'm going to close this.

**Closed by wirepair** 2016-03-09 09:15 UTC

**Comment by 5k3105** [comment] 2016-03-09 20:52
But it still doesn't work :(

**Comment by wirepair** [comment] 2016-03-10 01:28
Not exactly sure how else I can support you here, it's working in that it's executing and not returning errors. I can't really tell you why chrome is refusing to redraw the window.
